### ISSUE TITLE
Bug: Invisible units get shot by AI (toggle visibility module)

### ISSUE THREAD

**Issue by Adami50th** [mharis001/ZEN#11]
Using the Invisibility module will turn you invisible visually, but enemy AI can still target you and even try to shoot you as you're in the same faction as previously.
Perhaps it should move the invisible player or AI to the Civilian faction to avoid such situations?

**Comment by mharis001** [comment]
I agree, it would make sense for AI to not shoot an invisible unit. Adding `setCaptive` to the invisibility code should fix this.

**Comment by mharis001** [comment]
Looks like AI shot units that went invisible after they knew about them. Should be fixed by #18 .
